import fdb
conn = fdb.connect(dsn='localhost:C:/Nexus/Data/KSTRATOR.FDB', user='SYSDBA', password='masterkey')
c = conn.cursor()
c.execute("SELECT ID_PEDIDO, VALOR_PEDIDO, VALOR_FRETE, DESCONTO, VALOR_DESCONTO, ACRESCIMO, VALOR_ACRESCIMO, OUTRAS_DESPESAS, VALOR_SERVICOS FROM PEDIDOS WHERE DATA_HORA >= '2026-05-11' AND STATUS IN (0, 1, 2, 9)")
print("ID_PEDIDO, VALOR_PEDIDO, VALOR_FRETE, DESCONTO, VALOR_DESCONTO, ACRESCIMO, VALOR_ACRESCIMO, OUTRAS_DESPESAS, VALOR_SERVICOS")
for r in c.fetchall():
    print(r)
